common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from common.views import SignUpView


from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('ranking/', views.rankingpage, name='rankingpage'),
    path('introduction/', views.introductionpage, name='introductionpage'),
    path('calendar/', views.calendarpage, name='calendarpage'),
    path('mypage/', views.mypage, name='mypage'),

]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),

]

common/models.py
from django.db import models


class Users_info(models.Model):
    username= models.CharField(max_length=10)
    user_id = models.CharField(max_length=10)
    email = models.CharField(max_length=30)
    password1 = models.CharField(max_length=15)
    password2 = models.CharField(max_length=15)
    pin = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    weight = models.IntegerField(default=0)
    create_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user_info'

pybo/models.py
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    '''
    pin = forms.DecimalField(label="기기 핀번호")
    height = forms.DecimalField(label="키")
    weight = forms.DecimalField(label="몸무게")
    '''

    class Meta:
        model = User
        fields = ("username", "email")
        '''
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'pin': forms.NumberInput(attrs={'class': 'form-control'}),
            'height': forms.NumberInput(attrs={'class': 'form-control'}),
            'weight': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        '''

    '''
    def save(self, commit=True):  # 저장하는 부분 오버라이딩
        user = super(UserForm, self).save(commit=False)  # 본인의 부모를 호출해서 저장하겠다.
        user.email = self.cleaned_data["email"]
        
        user.pin = self.cleaned_data["pin"]
        user.height = self.cleaned_data["height"]
        user.weight = self.cleaned_data["weight"]
        
        if commit:
            user.save()
        return user
    '''

pybo/forms.py
from django import forms

from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

common/views.py
from django.shortcuts import render
import json

from django.views import View
from django.views.generic import TemplateView
from django.http import JsonResponse, HttpResponse
from .models import Users_info
import bcrypt


class SignUpView(View):
    def get(self,request):
        return render(request,'common/signup.html')

    def post(self, request):

        if request.META['CONTENT_TYPE'] == "application/json":
            request = json.loads(request.body)
            print(request)
        # if Users_info.objects.filter(user_id=data['id']).exists():
        #   return JsonResponse({"중복된 아이디 입니다."},status=400)
        else:
            data = Users_info(
                user_id=request.POST['user_id'],
                email=request.POST['email'],
                username=request.POST['username'],
                password1=request.POST['password1'],
                password2=request.POST['password2'],
                pin=request.POST['pin'],
                height=request.POST.get('height', 0),
                weight=request.POST.get('weight', 0),
                create_date=request.POST.get('create_date')
            )
            print(data)
        data.save()
        return render(request,'common/login.html')

    # def post(self, request):
    #     """
    #     계정생성
    #     """
    #     # if request.method == "POST":
    #     #     print("post")
    #     data = json.loads(request.body)
    #     #data = request.body
    #     print(data)
    #     password_not_hashed = data('password1')
    #     hashed_password = bcrypt.hashpw(password_not_hashed.encode("utf-8"), bcrypt.gensalt())
    #
    #     try:
    #
    #         Users_info(
    #             user_id =data['user_id'],
    #             email =data['email'],
    #             username =data['username'],
    #             password1 = hashed_password.decode("utf-8"),
    #             password2 = data['password2'],
    #             pin = data['pin'],
    #             weight =data['weight'],
    #             height =data['height']
    #         ).save()
    #
    #
    #         # 7.성공적으로 저장이 되었으면 성공 메시지를 보낸다.
    #         return JsonResponse({'message': '회원가입 성공'}, status=200)
    #
    #
    #     # 8.예외처리
    #     except KeyError:
    #         return JsonResponse({'message': "INVALID_KEYS"}, status=400)
    #
    #     return render(request, 'common/signup.html')

    # def get(self, request):
    #     user_data = Users_info.objects.values()
    #     return JsonResponse({'users':list(user_data)}, status=200)


def rankingpage(request):
    return render(request, 'common/ranking.html')


def introductionpage(request):
    return render(request, 'common/introduction.html')


def calendarpage(request):
    return render(request, 'common/calendar.html')


def mypage(request):
    return render(request, 'common/mypage.html')

pybo/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import QuestionForm, AnswerForm
from .models import Question


def index(request):
    """
    pybo 목록출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지

    # 조회
    question_list = Question.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    pybo 내용출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id):
    """
    pybo
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


def question_create(request):
    """
    pybo 질문등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>눈바디스마트미러에 오신것을 환영합니다</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        body{
            font-family: 'Do Hyeon', sans-serif;
    }
    </style>

</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/common/login.html
<head>
    <style>
        .form-group{
            margin: 100px auto 100px auto;
            width: 600px;
            height: 400px;
        }
        .id{
            margin-bottom: 30px;
        }
        .pw{
            margin-bottom: 30px;
        }
        .login-text{
            margin: 50px 0px;
            text-align:center;
        }

    </style>
</head>
{% extends "base.html" %}
{% block content %}
    <div class="container my-3">
        <div class ="login-text">
            <h3>로그인</h3>
        </div>
        <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <div class="id">
                <label for="username">사용자ID</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ forms.username.value|default_if_none:''}}">
            </div>
            <div class="pw">
                <label for="password">비밀번호</label>
                <input type="password" class="form-control" name="password" id="password"
                       value="{{ forms.password.value|default_if_none:''}}">
            </div>
            <button type="submit" class="btn btn-primary">로그인</button>
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>

    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<head>
        <style>
            #basic-addon1{
                width:200px;
            }


        </style>
</head>

<body>
    <div class="container my-3">
        <div class="row my-3">
            <div class="col-4">
                <h4>계정생성</h4>
            </div>
            <div class="col-8 text-right">
                <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
            </div>
        </div>
        <form method="post" class="post-form">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-group">
                <label for="username">사용자이름</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ models.username.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="username">아이디</label>
                <input type="text" class="form-control" name="user_id" id="user_id"
                       value="{{ models.user_id.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control" name="password1" id="password1"
                       value="{{ models.password1.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control" name="password2" id="password2"
                       value="{{ models.password2.value|default_if_none:'' }}">
            </div>

            <div class="form-group">
                <label for="device-number">기기 핀번호</label>
                <input type="number" class="form-control" name="pin" id="pin"
                        value="{{ models.pin.value|default_if_none:'' }}">
            </div>

            <div class="form-group">
                <label for="device-number">키</label>
                <input type="number" class="form-control" name="height" id="height"
                        value="{{ models.height.value|default_if_none:'' }}">
            </div>
            <div class="form-group">
                <label for="device-number">몸무게</label>
                <input type="number" class="form-control" name="weight" id="weight"
                        value="{{ models.weight.value|default_if_none:'' }}">
            </div>

            <div class="form-group">
                <label for="email">이메일</label>
                <input type="text" class="form-control" name="email" id="email"
                           value="{{ models.email.value|default_if_none:'' }}"}>
            </div>

            <button type="submit" class="btn btn-primary">생성하기</button>
        </form>
    </div>
</body>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<head>
    <style>
        .navbar navbar-expand-lg navbar-light bg-light border-bottom {
            list-style-type: none;
            padding: 10px;
        }

        @import url('https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap');
        body {
            font-family: 'Do Hyeon', sans-serif;
        }

        .nav-link {
            display: block;
        }
    </style>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</head>

<!--네비게이션바 &ndash;&gt;-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <a class="navbar-brand" href="{% url 'pybo:index' %}">
                <h1>
                    <img src="https://postfiles.pstatic.net/MjAyMTA3MTdfMzgg/MDAxNjI2NDQ5MjY3Mjgw.qm5d64aVfzHLpj3jNBZstj2MGBMeyJOMBcC6IZgOpEwg.6Ryh7lWZST3O1Xa0K43Wxw9pGUrjKzVrZwrWCYepSo8g.PNG.skawjdska235/logo.png?type=w773"
                         width="100" height="100" alt="">
                    눈바디스마트미러
                </h1>
            </a>


            <div class="navbar-nav">

                <a class="nav-item nav-link active" href="{% url 'pybo:index' %}">Home<span
                        class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'common:introductionpage' %}">Introduction</a>
                <a class="nav-item nav-link" href="{% url 'common:rankingpage' %}">Ranking</a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'common:mypage' %}">Mypage</a>
                    <a class="nav-item nav-link" href="{% url 'common:calendarpage' %}">Exercise Calendar</a>
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}"><b>로그인</b></a>
                {% endif %}

            </div>

        </div>
    </nav>


</nav>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>


</div>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list(1).html
    {% extends 'base.html' %}
    {% load pybo_filter %}
    {% block content %}
        <head>
            <style>
                .mirror{
                    width: 100%;
                    height: 100%;
                }
                .title-text{
                    text-align: center;
                    margin:50px;

                }
                .ranking-title{
                    margin-top: 50px;
                    display: block;

                }
            </style>

            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
            <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
            <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css" />

        </head>

    <div class="container my-3">
        <img src ="https://postfiles.pstatic.net/MjAyMTA3MTdfMTQg/MDAxNjI2NDQ4MDEzNzg0.jl3ZdnTPyG-eYN8BKtYaaiV0ol6QdxXgh0YklMK3JVYg.KlYO-_QuWwQjhVc2OsW6_UvaUV_ru06VBa3vvpEY3iMg.PNG.skawjdska235/facebook_cover_photo_1.png?type=w773" width="1110">
        <h1 class="title-text" style="font-size:50px ;">눈바디 스마트미러에 오신 것을 환영합니다!</h1>
        <div>
            <img src ="https://funshop.akamaized.net/abroad/027/13713/Ayi%20Smart%20mirror%203_1.jpg" class="mirror">
        </div>
    <table class="table">
        <h3 class="ranking-title">Ranking</h3>
        <thead>
        <tr class="thead-dark">
            <th>Ranking</th>
            <th>ID</th>
            <th>Record</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이징처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>



</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
    <head>
        <style>
            .mirror{
                width: 100%;
                height: 100%;
            }
            .title-text{
                text-align: center;
                margin:50px;

            }
            .ranking-title{
                margin-top: 50px;
                display: block;

            }
            .bottom-line{
                margin:50px;
            }
        </style>

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css" />

    </head>

    <div class="container my-3">
        <img src ="https://postfiles.pstatic.net/MjAyMTA3MTdfMTQg/MDAxNjI2NDQ4MDEzNzg0.jl3ZdnTPyG-eYN8BKtYaaiV0ol6QdxXgh0YklMK3JVYg.KlYO-_QuWwQjhVc2OsW6_UvaUV_ru06VBa3vvpEY3iMg.PNG.skawjdska235/facebook_cover_photo_1.png?type=w773" width="1110">
        <h1 class="title-text" style="font-size:50px ;">눈바디 스마트미러에 오신 것을 환영합니다!</h1>

        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src ="https://funshop.akamaized.net/abroad/027/13713/Ayi%20Smart%20mirror%203_1.jpg" class="mirror"alt="first slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="https://t1.daumcdn.net/liveboard/bizion/cd26d7d0580e4b848a3e887c550030e9.JPG" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="https://image.ajunews.com/content/image/2020/07/12/20200712172022555148.png" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <table class="table">
            <h3 class="ranking-title">Commuicate</h3>
            <thead>
            <tr class="thead-dark">
                <th>number</th>
                <th>Context</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            {% if question_list %}
                {% for question in question_list %}
                    <tr>
                        <td>
                            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                            {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                        </td>
                        <td>
                            <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                            {% if question.answer_set.count > 0 %}
                                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                            {% endif %}
                        </td>
                        <td>{{ question.create_date }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">질문이 없습니다.</td>
                </tr>
            {% endif %}
            </tbody>
        </table>

        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in question_list.paginator.page_range %}
                {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                    {% if page_number == question_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
            {% endif %}
        </ul>

        <!-- 페이징처리 끝 -->
        <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        <hr color="gray" class="bottom-line" align="center">
    </div>
{% endblock %}